### ISSUE TITLE
Something went wrong during installation

### ISSUE THREAD

**Issue by NorseGaud** [ONLYOFFICE/snap-documentserver#14]
Hello, I've installed onlyoffice-ds using snap and I see "Something went wrong during installation" when I visit my domain and the port. 

I'm on `Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-62-generic x86_64)`

I don't see any logs about why from the little I've poked around. Where should I look? Does anyone have any suggestions?

<img width="976" alt="Screen Shot 2019-09-28 at 6 58 05 PM" src="https://user-images.githubusercontent.com/5896030/65823323-f0026e00-e221-11e9-89aa-fc56412d203d.png">

**Comment by NorseGaud** [comment]
Found a log (finally) ```
==> /var/snap/onlyoffice-ds/current/var/log/onlyoffice/documentserver/docservice/out.log <==
[2019-10-29T07:12:41.311] [ERROR] nodeJS - pool.getConnection error: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'onlyoffice'@'localhost' (using password: YES)
[2019-10-29T07:12:41.312] [ERROR] nodeJS - healthCheck error
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'onlyoffice'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
```

**Comment by NorseGaud** [comment]
I remembered I run mysql through other snap packages, so I changed the port to 3307. That didn't help either though... 

So I went digging for a mysql log and found it!
```
2019-10-29T11:15:15.059845Z 0 [Note] InnoDB: Waiting for purge to start
2019-10-29T11:15:15.109987Z 0 [Note] InnoDB: 5.7.27 started; log sequence number 1209961
mysqld: Table 'mysql.plugin' doesn't exist
2019-10-29T11:15:15.110364Z 0 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
2019-10-29T11:15:15.110680Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/snap/onlyoffice-ds/10/mysql/ib_buffer_pool
2019-10-29T11:15:15.110700Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2019-10-29T11:15:15.110774Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
2019-10-29T11:15:15.110782Z 0 [Note] Server hostname (bind-address): '*'; port: 3307
2019-10-29T11:15:15.110842Z 0 [Note] IPv6 is available.
2019-10-29T11:15:15.110851Z 0 [Note]   - '::' resolves to '::';
2019-10-29T11:15:15.110869Z 0 [Note] Server socket created on IP: '::'.
2019-10-29T11:15:15.110922Z 0 [Note] InnoDB: Buffer pool(s) load completed at 191029  7:15:15
2019-10-29T11:15:15.141681Z 0 [Warning] Insecure configuration for --pid-file: Location '/tmp' in the path is accessible to all OS users. Consider choosing a different directory.
2019-10-29T11:15:15.141813Z 0 [Warning] Failed to open optimizer cost constant tables

2019-10-29T11:15:15.141914Z 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
2019-10-29T11:15:15.141931Z 0 [ERROR] Fatal error: Failed to initialize ACL/grant/time zones structures or failed to remove temporary table files.
2019-10-29T11:15:15.142000Z 0 [ERROR] Aborting
```

**Comment by NorseGaud** [comment]
@agolybev  Any ideas why this wouldn't be working?

**Comment by NorseGaud** [comment]
@Igor-Pigalitsyn 

```
root@deliver:~# snap info onlyoffice-ds
name:      onlyoffice-ds
summary:   An online office suite that allowing to create, view and edit documents.
publisher: Ascensio System SIA (onlyoffice✓)
contact:   https://github.com/ONLYOFFICE/snap-documentserver/issues
license:   unset
description: |
  ONLYOFFICE Document Server is an online office suite comprising viewers and editors for texts,
  spreadsheets and presentations, fully compatible with Office Open XML formats: .docx, .xlsx, .pptx
  and enabling collaborative editing in real time.
commands:
  - onlyoffice-ds.mysql-client
  - onlyoffice-ds.mysqldump
  - onlyoffice-ds.node
services:
  onlyoffice-ds.documentserver: simple, enabled, active
  onlyoffice-ds.mysql:          simple, enabled, active
  onlyoffice-ds.nginx:          simple, enabled, active
  onlyoffice-ds.rabbitmq:       simple, enabled, active
  onlyoffice-ds.redis:          simple, enabled, active
snap-id:      zZWL0GK8BltYmYJcaTUQro9X2Rd6yVaN
tracking:     stable
refresh-date: today at 20:10 EDT
channels:
  stable:    5.4.0 2019-10-28 (10) 595MB -
  candidate: 5.4.0 2019-10-28 (10) 595MB -
  beta:      5.4.0 2019-10-24 (10) 595MB -
  edge:      5.4.1 2019-10-29 (12) 595MB -
installed:   5.4.0            (10) 595MB -
```

**Comment by guoguoguilai** [comment]
> @Igor-Pigalitsyn
> 
> ```
> root@deliver:~# snap info onlyoffice-ds
> name:      onlyoffice-ds
> summary:   An online office suite that allowing to create, view and edit documents.
> publisher: Ascensio System SIA (onlyoffice✓)
> contact:   https://github.com/ONLYOFFICE/snap-documentserver/issues
> license:   unset
> description: |
>   ONLYOFFICE Document Server is an online office suite comprising viewers and editors for texts,
>   spreadsheets and presentations, fully compatible with Office Open XML formats: .docx, .xlsx, .pptx
>   and enabling collaborative editing in real time.
> commands:
>   - onlyoffice-ds.mysql-client
>   - onlyoffice-ds.mysqldump
>   - onlyoffice-ds.node
> services:
>   onlyoffice-ds.documentserver: simple, enabled, active
>   onlyoffice-ds.mysql:          simple, enabled, active
>   onlyoffice-ds.nginx:          simple, enabled, active
>   onlyoffice-ds.rabbitmq:       simple, enabled, active
>   onlyoffice-ds.redis:          simple, enabled, active
> snap-id:      zZWL0GK8BltYmYJcaTUQro9X2Rd6yVaN
> tracking:     stable
> refresh-date: today at 20:10 EDT
> channels:
>   stable:    5.4.0 2019-10-28 (10) 595MB -
>   candidate: 5.4.0 2019-10-28 (10) 595MB -
>   beta:      5.4.0 2019-10-24 (10) 595MB -
>   edge:      5.4.1 2019-10-29 (12) 595MB -
> installed:   5.4.0            (10) 595MB -
> ```
> 
> I seem to be using the most recent version, yet, it still fails to start MYSQL

Have you solved this problem?

**Comment by NorseGaud** [comment]
> > @Igor-Pigalitsyn
> > ```
> > root@deliver:~# snap info onlyoffice-ds
> > name:      onlyoffice-ds
> > summary:   An online office suite that allowing to create, view and edit documents.
> > publisher: Ascensio System SIA (onlyoffice✓)
> > contact:   https://github.com/ONLYOFFICE/snap-documentserver/issues
> > license:   unset
> > description: |
> >   ONLYOFFICE Document Server is an online office suite comprising viewers and editors for texts,
> >   spreadsheets and presentations, fully compatible with Office Open XML formats: .docx, .xlsx, .pptx
> >   and enabling collaborative editing in real time.
> > commands:
> >   - onlyoffice-ds.mysql-client
> >   - onlyoffice-ds.mysqldump
> >   - onlyoffice-ds.node
> > services:
> >   onlyoffice-ds.documentserver: simple, enabled, active
> >   onlyoffice-ds.mysql:          simple, enabled, active
> >   onlyoffice-ds.nginx:          simple, enabled, active
> >   onlyoffice-ds.rabbitmq:       simple, enabled, active
> >   onlyoffice-ds.redis:          simple, enabled, active
> > snap-id:      zZWL0GK8BltYmYJcaTUQro9X2Rd6yVaN
> > tracking:     stable
> > refresh-date: today at 20:10 EDT
> > channels:
> >   stable:    5.4.0 2019-10-28 (10) 595MB -
> >   candidate: 5.4.0 2019-10-28 (10) 595MB -
> >   beta:      5.4.0 2019-10-24 (10) 595MB -
> >   edge:      5.4.1 2019-10-29 (12) 595MB -
> > installed:   5.4.0            (10) 595MB -
> > ```
> > 
> > 
> > I seem to be using the most recent version, yet, it still fails to start MYSQL
> 
> Have you solved this problem?

No. Nothing I do seems to work.

**Comment by NorseGaud** [comment]
Ok, I tried edge and it looks like it doesn't fail outright, but does throw:

```Version: '5.7.27'  socket: '/tmp/mysql.sock'  port: 3307  MySQL Community Server (GPL)
2019-11-08T12:52:46.181264Z 2 [Note] Access denied for user 'onlyoffice'@'localhost' (using password: YES)```

**Comment by NorseGaud** [comment]
It's seemingly more and more like the https://github.com/ONLYOFFICE/snap-documentserver/blob/master/src/mysql/bin/start_mysql isn't setting the password properly.

**Comment by guoguoguilai** [comment]
Solved. It works just fine. No wget this page.

**Comment by chagwood** [comment]
I also could not get the onlyoffice-ds snap to work.

I also tried using the edge channel.

Getting this from the error.log in /var/snap/onlyoffice-ds/current/mysql
` Access denied for user 'onlyoffice'@'localhost' (using password: YES)`

I'm on ubuntu server 19.10

**Comment by nebriv** [comment]
I am also having similar issues on Ubuntu 18.04. Can I provide anything to help troubleshoot?

**Comment by nebriv** [comment]
I was able to resolve the problem by opening current/etc/onlyoffice/documentserver/local.json, get the password and then set the password via sudo onlyoffice-ds.mysql-client. 

Hope that helps anyone else!

**Comment by orlovnv** [comment]
have the same problem, how to solve it?

**Comment by CacheMinimal** [comment]
I have just experienced the same issue using this snap on several Ubuntu 18.04.3 servers.  In my case it was caused by the server already having a MySQL installation running on port 3306.  I used the following steps to make it work:

1. Remove the snap with `sudo snap remove onlyoffice-ds`
2. Stop the existing MySQL service with `sudo systemctl stop mysql.service`
3. Reinstall the snap with `sudo snap install onlyoffice-ds`
4. Set the snap-based MySQL port with `sudo snap set onlyoffice-ds onlyoffice.db-port=3307`
5. Restart the original MySQL service with `sudo systemctl start mysql.service`
6. Verify that both MySQL instances are running with `sudo netstat -tlpn | grep 330.`

As the snap install script is configured to use port 3306 by default it clashes with the existing MySQL installation.  The snap-based MySQL fails to start as the port is in use.  The install script then tries, unsuccessfully as it does not know the MySQL root password, to configure the previous MySQL instance.  By stopping the original MySQL installation we can work around this.  It would be better if the snap defaulted to using an custom port (like 33306) for the snap-based MySQL instance to avoid the need to do this.

**Comment by orlovnv** [comment]
try to do like you suggest, but no success, I even try to stop Nginx and change its port to 8888 in snap. I did all in Debian buster

**Comment by cldtech** [comment]
Read everything from the beginning, tried every suggestions.
On Ubuntu 18.04 fresh install then `snap install onlyoffice-ds`.

Here's what's print in /var/snap/onlyoffice-ds/current/var/log/onlyoffice/documentserver/docservice every time i restart onlyoffice-ds;
`[2020-02-13T04:21:57.602] [WARN] nodeJS - Plugins watch exception (https://nodejs.org/docs/latest/api/fs.html#fs_availability).
[2020-02-13T04:21:57.716] [WARN] nodeJS - update cluster with 1 workers
[2020-02-13T04:21:57.816] [WARN] nodeJS - worker 32134 started.
[2020-02-13T04:21:57.843] [WARN] nodeJS - update cluster with 1 workers
[2020-02-13T04:22:00.361] [WARN] nodeJS - Express server starting...
[2020-02-13T04:22:01.859] [WARN] nodeJS - Express server listening on port 8000 in production-linux mode
[2020-02-13T04:22:18.344] [ERROR] nodeJS - pool.getConnection error: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'onlyoffice'@'localhost' (using password: YES)
[2020-02-13T04:22:18.354] [ERROR] nodeJS - healthCheck error
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'onlyoffice'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
    --------------------
    at Protocol._enqueue (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/mysql/lib/Pool.js:48:16)
    at Object.exports.sqlQuery (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/sources/mySqlBaseConnector.js:29:7)
    at /snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/sources/baseConnector.js:228:19
    at new Promise (<anonymous>)
    at Object.exports.healthCheck (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/sources/baseConnector.js:227:10)
    at /snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:2837:29
    at Generator.next (<anonymous>)
    at onFulfilled (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:65:19)
    at /snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/co/index.js:50:10)
    at exports.healthCheck (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/sources/DocsCoServer.js:2832:10)
    at Layer.handle [as handle_request] (/snap/onlyoffice-ds/10/var/www/onlyoffice/documentserver/server/DocService/node_modules/express/lib/router/layer.js:95:5)
`

**Comment by CacheMinimal** [comment]
@cldtech, can I recommend removing the snap with `sudo snap remove onlyoffice-ds`.  You can then run the following command to check all the ports the documentserver snap uses:

`sudo netstat -tlpn | grep ':80 \|:3306 \|:5672 \|:6379 \|:8000 \|:8080'`

If everything is good for the snap installation you should receive no output from this command.  Otherwise you will see an ID and image name for the process that is currently using the port.  You will need to stop this service (or services), install the snap, update the port(s) the snap uses to (an)other one(s) and then restart the original service(s).

In this way it should be possible to get the snap installed.  Be wary of #32 as well at the moment though.  Docker support for documentserver seems much more responsive for some reason.

**Comment by cldtech** [comment]
> @cldtech, can I recommend removing the snap with `sudo snap remove onlyoffice-ds`. You can then run the following command to check all the ports the documentserver snap uses:
> 
> `sudo netstat -tlpn | grep ':80 \|:3306 \|:5672 \|:6379 \|:8000 \|:8080'`
> 
> If everything is good for the snap installation you should receive no output from this command. Otherwise you will see an ID and image name for the process that is currently using the port. You will need to stop this service (or services), install the snap, update the port(s) the snap uses to (an)other one(s) and then restart the original service(s).
> 
> In this way it should be possible to get the snap installed. Be wary of #32 as well at the moment though. Docker support for documentserver seems much more responsive for some reason.

Wonderful! I had tried this from your last response 10 days ago but not with all those ports! First time i see all those Thank you! Working for me now.
